name: ryu-cho

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch: # on button click

jobs:
  ryu-cho:
    name: Ryu Cho
    runs-on: ubuntu-latest
    steps:
      - uses: vuejs-translations/ryu-cho@v1
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          username: ${{ secrets.RYU_CHO_USER_NAME }}
          email: ${{ secrets.RYU_CHO_USER_EMAIL }}
          upstream-repo: https://github.com/vuejs-translations/docs-fa.git
          upstream-repo-branch: main
          head-repo: https://github.com/vuejs/docs
          head-repo-branch: main
          track-from: ca5f159ab3ab80fb5b2122a98bc0f428eec4cb8d
          # path-starts-with: src/
          workflow-name: ryu-cho
